name = "emmiwood-barbers-preview"
compatibility_date = "2026-07-01"
pages_build_output_dir = "client/dist"

[[d1_databases]]
binding = "DB"
database_name = "emmiwood-standalone-preview-db"
database_id = "b4a10012-e0c8-40f0-b203-31474393fb2a"
migrations_dir = "migrations"
